### ISSUE TITLE
博客地址重定向错误

### ISSUE THREAD

**Issue by hmgle** [blogbar/blogbar#40]
例如这个地址: http://www.blogbar.cc/blog/post/4393/redirect 会重定向到 http://hmgle.github.io/hmgle.github.io/erlang/2014/12/09/erlang-zebra.html
正确的地址应该是 http://hmgle.github.io/erlang/2014/12/09/erlang-zebra.html

**Comment by hustlzp** [comment]
你好，我看到 http://hmgle.github.io/feed.xml 中的 link 如下：

```
<link>
hmgle.github.io/erlang/2014/12/09/erlang-zebra.html
</link>
```

能否在 link 开头加上 `http://` ？

**Comment by hmgle** [comment]
哦, 原来是这样.
已修复 http://hmgle.github.io 的 site.url 了~
